# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        # the following files requires to have a trailing space/tab
        # to test how byexample handle those cases
        exclude: |
            (?x)^(
                byexample/modules/java.py|
                byexample/modules/ruby.py|
                docs/advanced/terminal-emulation.md
            )$

    -   id: check-added-large-files

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.31.0
    hooks:
    -   id: yapf
        args: [-i, --style=.style.yapf]
        files: ^byexample/

-   repo: https://github.com/commitizen-tools/commitizen
    # Install:
    #   pre-commit install --hook-type commit-msg
    # commit type:
    #   build: think in Makefile
    #   ci: think in pre-commit or github hooks
    #   docs
    #   feat
    #   fix
    #   perf
    #   refactor: think in changes that does not change output but code itself
    #   style
    #   test
    #   chore: used as a fallback, a lot overlap with build and ci
    #   revert
    #   bump: bump a new version
    rev: v2.29.0
    hooks:
    -   id: commitizen
