-   id: byexample
    name: Run code snippets to validate them
    description: Execute code snippets in your documentation and validate them as regression tests. Your docs will never be outdated again. See https://byexamples.github.io/byexample/recipes/pre-commit
    entry: byexample
    language: python
    require_serial: true
    pass_filenames: true
