branches:
    only:
        - master
        - next-major
        - next-minor
        - next-patch
        - tmp

env:
    global:
      - BYEXAMPLE_CACHE_DISABLED=0
      - 'PYTHONWARNINGS=ignore:::byexample.cache'

install: make deps
script: make test

matrix:
    include:
        - name: "Github pages"
          language: ruby
          rvm:
            - 2.1
          install: "echo ok"
          script:
            - 'echo -e ''source "https://rubygems.org"\ngem "github-pages"'' > Gemfile'
            - "bundle install && cd docs && bundle exec jekyll build"
            - "make index-links-test"
        - language: python
          python: "2.7"
        - language: python
          python: "3.5"
        - language: python
          python: "3.6"
        - language: python
          python: "3.7"
          dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
        - language: ruby
          rvm: "2.0"
          install: sudo make deps
          script: make travis-ruby-test
        - language: ruby
          rvm: "2.1"
          install: sudo make deps
          script: make travis-ruby-test
        - language: ruby
          rvm: "2.2"
          install: sudo make deps
          script: make travis-ruby-test
        - language: ruby
          rvm: "2.3"
          install: sudo make deps
          script: make travis-ruby-test
        - language: ruby
          rvm: "2.4"
          install: sudo make deps
          script: make travis-ruby-test
        - language: ruby
          rvm: "2.5"
          install: sudo make deps
          script: make travis-ruby-test
        - language: ruby
          rvm: "2.6"
          install: sudo make deps
          script: make travis-ruby-test
