language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
      # - "3.7" travis doesn't support this yet
install: make deps
script: make travis-test
branches:
    only:
        - master
        - next
addons:
    apt_packages:
        - pandoc
env:
    global:
        - languages=python,shell
        - BYEXAMPLE_CACHE_DISABLED=0

matrix:
    include:
        - name: "Github pages"
          language: ruby
          rvm:
            - 2.1
          install: "echo ok"
          script:
            - 'echo -e ''source "https://rubygems.org"\ngem "github-pages"'' > Gemfile'
            - "bundle install && cd docs && bundle exec jekyll build"
