branches:
    only:
        - master
        - next-major
        - next-minor
        - next-patch
        - tmp
        - one-docker-to-rule-em-all

env:
    global:
      - BYEXAMPLE_CACHE_DISABLED=0
      - 'PYTHONWARNINGS=ignore:::byexample.cache'

install: make deps-dev
script: make test

matrix:
    include:
        - name: "Github pages"
          language: ruby
          rvm:
            - 2.1
          install: "echo ok"
          script:
            - "make index-links-test"
            - 'echo -e ''source "https://rubygems.org"\ngem "github-pages"'' > Gemfile'
            - "bundle install && cd docs && bundle exec jekyll build"
        - name: "Source code format"
          language: python
          python: "3.5"
          script: make format-test
        - language: python
          python: "3.5"
        - language: python
          python: "3.6"
        - language: python
          python: "3.7"
        - language: python
          python: "3.8"
        - language: python
          python: "3.9-dev"
        - language: ruby
          rvm: "2.0"
          install:
              - 'eval "$(pyenv init -)"'
              - 'pyenv global $(pyenv versions | grep ''^\s*3\.'' | head -1)'
              - "make deps-dev"
          script: make travis-ruby-test
        - language: ruby
          rvm: "2.1"
          install:
              - 'eval "$(pyenv init -)"'
              - 'pyenv global $(pyenv versions | grep ''^\s*3\.'' | head -1)'
              - "make deps-dev"
          script: make travis-ruby-test
        - language: ruby
          rvm: "2.2"
          install:
              - 'eval "$(pyenv init -)"'
              - 'pyenv global $(pyenv versions | grep ''^\s*3\.'' | head -1)'
              - "make deps-dev"
          script: make travis-ruby-test
        - language: ruby
          rvm: "2.3"
          install:
              - 'eval "$(pyenv init -)"'
              - 'pyenv global $(pyenv versions | grep ''^\s*3\.'' | head -1)'
              - "make deps-dev"
          script: make travis-ruby-test
        - language: ruby
          rvm: "2.4"
          install:
              - 'eval "$(pyenv init -)"'
              - 'pyenv global $(pyenv versions | grep ''^\s*3\.'' | head -1)'
              - "make deps-dev"
          script: make travis-ruby-test
        - language: ruby
          rvm: "2.5"
          install:
              - 'eval "$(pyenv init -)"'
              - 'pyenv global $(pyenv versions | grep ''^\s*3\.'' | head -1)'
              - "make deps-dev"
          script: make travis-ruby-test
        - language: ruby
          rvm: "2.6"
          install:
              - 'eval "$(pyenv init -)"'
              - 'pyenv global $(pyenv versions | grep ''^\s*3\.'' | head -1)'
              - "make deps-dev"
          script: make travis-ruby-test
