name: test
on: [pull_request]
jobs:
  byexample-test:
    name: "Byexample Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            python-version: ["3.5", "3.6", "3.7", "3.8", "3.9"]
            os: ["ubuntu-latest"]
    env:
        TERM: xterm-color
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: make deps-dev
      - run: make lib-test
      - run: make modules-test
      - run: make docs-test

  source-code-test:
    name: "Source code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.5"
      - run: make deps-dev
      - run: make format-test

  github-pages-test:
    name: "Github Pages test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - run: make index-links-test
      - run: ./test/github-pages.sh

  lang-python-test:
    name: "Lang Python test"
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: ["3.5", "3.6", "3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: make deps-dev
      - run: make lang-python-test

  lang-ruby-test:
    name: "Lang Ruby test"
    runs-on: ubuntu-latest
    strategy:
        matrix:
            ruby-version: ["2.4", "2.5", "2.6"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.5"
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: make deps-dev
      - run: make lang-ruby-test
