name: test
on: [pull_request]
jobs:
  byexample-test:
    name: "Byexample Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: ["3.6", "3.7", "3.8", "3.9"]
    env:
        TERM: xterm-color
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: make deps-dev
      - run: make lib-test
      - run: make modules-test
      - run: make docs-test
      - run: make examples-test

  source-code-test:
    name: "Source code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - run: make deps-dev
      - run: make format-test

  github-pages-test:
    name: "Github Pages test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - run: make index-links-test
      - run: ./test/github-pages.sh

  lang-python-test:
    name: "Lang Python test"
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: ["3.6", "3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: make deps-dev
      - run: make lang-python-test

  lang-iasm-test:
    name: "Lang iasm test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - run: make deps-dev
      - run: pip install iasm
      - run: make lang-iasm-test

  lang-pwsh-test:
    name: "Lang PowerShell test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - run: make deps-dev
      - run: make lang-pwsh-test

  lang-ruby-test:
    name: "Lang Ruby test"
    runs-on: ubuntu-latest
    strategy:
        matrix:
            ruby-version: ["2.4", "2.5", "2.6", "2.7", "3.0"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: make deps-dev
      - run: make lang-ruby-test

  lang-shell-test:
    name: "Lang Shell test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - run: make deps-dev
      - run: make lang-shell-test

  lang-javascript-test:
    name: "Lang Javascript test"
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [10.x, 12.x, 14.x, 15.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: make deps-dev
      - run: make lang-javascript-test

  lang-go-test:
    name: "Lang Go test"
    runs-on: ubuntu-latest
    strategy:
        matrix:
            go-version: ["1.14", "1.13"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: make deps-dev
      - run: go get -u github.com/traefik/yaegi/cmd/yaegi
      - run: PATH=$PATH:$(go env GOPATH)/bin  make lang-go-test

  lang-java-test:
    name: "Lang Java test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '13', '15' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - run: make deps-dev
      - run: make lang-java-test
